before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: DWSF1pddYBF8MQLDOv5XMNZufdhU3nY1Qe8s52GeOGc844f6sCnjuQYC57jUQV/+nh2iGyQO1+4MkUSB1Sn8YlIoThVYzl/60JHetbsJkDsYjDZ2OvM+m6YIIg/Bj4x6oLqN/krzjRCJ0OdeHUvmBWNMb+xrLi6RZ41+ZQDQImY7VhI9k8rU+qqKk5NxNroaiowgxxnKR0Tt9OhLOoxJGNxvCEDqbaAdsSJPcWbTw0wkEiWO0WiiPy4TC3ZYThGTjDBCXbeGfcMPKei28Y1a0ZKg57HHeLCLZ2Cr4ppbp1Td/eI5VxtqfAaUiNU3bRWxPmxm/f7tb1QkwpjXN5Jrgc6pcV+xXWt9EO3WaVqpje1k0snySQYJ4xAtyYzLqBXSG+TiebyB1kLAoIRyJX6FXHTzy8TRDlteLE2Rv/zuII2/5WJWEzR8Wi8KPYa0HeS6mmEjZHppweTqdfE06SKNlEIffmJk2XhWTpZ5a8aQ6kWvUX050mvVhpnOKWqRbdTjm6z/uQu+WIxKyDWY9Xt2PdbMDLILePvVi3OKVZQhOSCcSRZ8fPnp2zQVFre9J0ZydIfVlnqgk3wEyFWayBHXCN9JpxUs0eRbAJDCV4YP6jyiYDxIoaj9+wHZ9dhWWUBphgSrYNbERfvAykjCJXCMDYhWORJtEKyGMBOAGmw7mEA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
